@important
Feature: DVD Rentals Segmentation and Engagement
  In order to increase the revenue generated by the business, I first need to identify the countries where the most of the revenue is coming from. Furthermore, I need to capture all US users who have paid less than the overall average amount. The intention here is to incentivize these users by using the Experian's Integrated Email Marketing service to send an email with a special offer coupon code.

  Scenario: User Segmentation
    Given that the user has access to the Postgres database