@important
Feature: DVD Rentals Segmentation and Engagement
  In order to increase the revenue generated by the business, I first need to identify the countries where the most of the revenue is coming from.
  Furthermore, I need to capture all US users who have paid less than the overall average amount.
  The intention here is to incentivize these users by using the Experian's Integrated Email Marketing service to send an email with a special offer coupon code.

  Background: Access PostgreSQL Database
    Given a user is connected to the DVD rental PostgreSQL database

  @regression @sanity
  Scenario: Revenue Identification
    When an SQL query has been developed to get the countries where most revenue is generated
    Then execute the country by revenue query
    And verify that United States is one of the top 3 earners
    And print data pertaining to the top 3 countries that bring in the most revenue

  @regression
  Scenario: User Segmentation
    When an SQL query has been developed to get all United States users who have paid less than the overall average amount
    Then execute the user segmentation query
    And verify that all user email addresses are not blank or empty
    And verify that all user email addresses are valid